"""Replacement tables.

Three tiers, gated by the level slider:

  TIER_SAFE   (level >= 1)  meaning-preserving de-bloating. "utilize" -> "use".
  TIER_CASUAL (level >= 3)  plainer, more spoken register. "numerous" -> "a lot of".
  TIER_LOOSE  (level >= 6)  register shifts that change the voice noticeably.

Each entry maps a source pattern to a list of candidate replacements; one is
picked at random, so the same word does not get rewritten the same way twice in
a document. Longer keys are always tried before shorter ones.
"""

from __future__ import annotations

# --------------------------------------------------------------------------
# Multi-word phrases. Matched case-insensitively on word boundaries.
# --------------------------------------------------------------------------

PHRASES_SAFE = {
    "in order to": ["to"],
    "in order for": ["for"],
    "due to the fact that": ["because", "since"],
    "owing to the fact that": ["because", "since"],
    "despite the fact that": ["even though", "although"],
    "in spite of the fact that": ["even though", "although"],
    "for the purpose of": ["for", "to"],
    "with the exception of": ["except for", "apart from"],
    "in the event that": ["if"],
    "in the event of": ["if there is"],
    "at this point in time": ["right now", "now"],
    "at the present time": ["right now", "now"],
    "in today's world": ["these days", "today"],
    "in today's fast-paced world": ["these days", "nowadays"],
    "in the modern era": ["these days", "today"],
    "in recent years": ["lately", "over the past few years"],
    "it is important to note that": ["note that", "keep in mind that", ""],
    "it is worth noting that": ["worth noting,", "note that", ""],
    "it should be noted that": ["note that", ""],
    "it is essential to": ["you need to", "you have to"],
    "it is crucial to": ["you need to", "you have to"],
    "it is imperative that": ["it matters that"],
    # The adjective has to come with it. Swapping "one of the most" alone
    # leaves "one of the biggest significant obstacles".
    "one of the most significant": ["one of the biggest", "one of the main"],
    "one of the most important": ["one of the biggest", "one of the main"],
    "one of the most crucial": ["one of the biggest", "one of the main"],
    "one of the most challenging": ["one of the hardest", "one of the toughest"],
    "one of the most effective": ["one of the best"],
    "a wide range of": ["a lot of", "many", "all kinds of"],
    "a wide variety of": ["all kinds of", "lots of"],
    "a broad range of": ["lots of", "many"],
    "a significant number of": ["a lot of", "quite a few"],
    "a substantial amount of": ["a lot of"],
    "a plethora of": ["a ton of", "lots of"],
    "a myriad of": ["tons of", "lots of"],
    "the vast majority of": ["most", "nearly all"],
    "a variety of": ["different", "all sorts of"],
    "an array of": ["a bunch of", "a set of"],
    "plays a crucial role in": ["is central to", "matters a lot for"],
    "plays a key role in": ["is central to", "matters a lot for"],
    "plays a vital role in": ["is central to", "really matters for"],
    "plays a significant role in": ["matters a lot for"],
    "serves as a": ["is a", "works as a"],
    "serve as a": ["are a", "work as a"],
    "is a testament to": ["shows", "says a lot about"],
    "stands as a testament to": ["shows"],
    "delve into": ["dig into", "get into", "look at", "unpack"],
    "delving into": ["digging into", "getting into"],
    "embark on": ["start", "kick off"],
    "embarking on": ["starting"],
    "navigate the complexities of": ["work through", "deal with"],
    "navigating the complexities of": ["working through", "dealing with"],
    "shed light on": ["explain", "clear up"],
    "gain insight into": ["understand", "get a feel for"],
    "gain insights into": ["understand", "get a feel for"],
    "in conclusion": ["so", "all in all", "to wrap up"],
    "in summary": ["so", "all in all", "to sum up"],
    "to summarize": ["to sum up", "so"],
    "as previously mentioned": ["like I said", "as mentioned"],
    "as mentioned earlier": ["like I said earlier", "as noted"],
    "first and foremost": ["first off", "first"],
    "last but not least": ["finally", "and last"],
    "on the other hand": ["then again", "but", "that said"],
    "in addition to": ["besides", "on top of"],
    "in addition,": ["also,", "plus,", "and"],
    "in contrast,": ["but", "then again,"],
    "by contrast,": ["but", "then again,"],
    "as a result of": ["because of"],
    "as a result,": ["so", "because of that,"],
    "for this reason,": ["so", "that's why"],
    "with regard to": ["about", "on"],
    "with respect to": ["about", "on"],
    "in relation to": ["about", "compared to"],
    "in terms of": ["when it comes to", "for"],
    "in the context of": ["in", "when it comes to"],
    "when it comes to the": ["with the"],
    "prior to": ["before"],
    "subsequent to": ["after"],
    "in the near future": ["soon", "before long"],
    "on a regular basis": ["regularly", "often"],
    "on a daily basis": ["daily", "every day"],
    "in a timely manner": ["quickly", "on time"],
    "in an effort to": ["to", "trying to"],
    "with the aim of": ["to"],
    "has the ability to": ["can"],
    "have the ability to": ["can"],
    "has the potential to": ["could", "might"],
    "have the potential to": ["could", "might"],
    "is able to": ["can"],
    "are able to": ["can"],
    "make use of": ["use"],
    "makes use of": ["uses"],
    "take into account": ["consider", "factor in"],
    "takes into account": ["considers", "factors in"],
    "take into consideration": ["consider"],
    "a large number of": ["many", "a lot of"],
    "the fact that": ["that"],
    "there is a need to": ["we need to", "you need to"],
    "it can be seen that": ["you can see that", ""],
    "this allows for": ["this lets you", "this means"],
    "allows for": ["lets you", "means"],
    "allowing for": ["letting you"],
    "aims to": ["tries to", "sets out to"],
    "aim to": ["try to", "set out to"],
    "seeks to": ["tries to"],
    "in many cases": ["often", "a lot of the time"],
    "in some cases": ["sometimes"],
    "in most cases": ["usually", "most of the time"],
    "a key factor": ["a big factor", "one big reason"],
    "an integral part of": ["a core part of", "central to"],
    "the ever-evolving": ["the changing", "the shifting"],
    "ever-evolving": ["changing", "shifting"],
    "cutting-edge": ["new", "advanced"],
    "state-of-the-art": ["top of the line", "modern"],
    "game-changer": ["big deal", "turning point"],
    "game changer": ["big deal", "turning point"],
    "deep dive": ["close look", "deep look"],
    "at the end of the day": ["in the end", "ultimately"],
    "moving forward": ["going forward", "from here"],
    "that being said": ["that said", "still"],
    "needless to say": ["obviously", "of course"],
    "the landscape of": ["the world of", "the state of"],
    "the realm of": ["the world of", "the area of"],
    "a rich tapestry of": ["a mix of", "a blend of"],
    "a tapestry of": ["a mix of", "a blend of"],
}

PHRASES_CASUAL = {
    "however,": ["but", "though,", "that said,"],
    "therefore,": ["so", "that means"],
    "furthermore,": ["also,", "on top of that,", "and"],
    "moreover,": ["also,", "plus,", "and"],
    "additionally,": ["also,", "plus,", "and"],
    "consequently,": ["so", "because of that,"],
    "nevertheless,": ["still,", "even so,"],
    "nonetheless,": ["still,", "even so,"],
    "subsequently,": ["then", "after that,"],
    "ultimately,": ["in the end,", "eventually,"],
    # Adverbs only. "a lot" follows the verb it modifies, so swapping it in for
    # "significantly" ahead of one gives "quite a bit reduce".
    "significantly": ["sharply", "notably", "massively"],
    "substantially": ["sharply", "hugely"],
    "approximately": ["about", "around", "roughly"],
    "a number of": ["a few", "several", "some"],
    "as well as": ["and", "plus"],
    "such as": ["like"],
    "for instance": ["for example", "say"],
    "that is to say": ["meaning", "in other words"],
    "in other words": ["put another way", "meaning"],
    "a great deal of": ["a lot of"],
    "quite a bit of": ["a lot of"],
    "is known as": ["is called"],
    "are known as": ["are called"],
    "is referred to as": ["is called"],
    "give rise to": ["cause", "lead to"],
    "gives rise to": ["causes", "leads to"],
    "result in": ["lead to", "cause"],
    "results in": ["leads to", "causes"],
    "in accordance with": ["following", "in line with"],
    "on the contrary": ["actually", "if anything"],
    "to a certain extent": ["somewhat", "to a point"],
    "to some extent": ["somewhat", "to a point"],
    "a form of": ["a kind of", "a type of"],
    "by means of": ["with", "through"],
    "in light of": ["given", "because of"],
    "regardless of whether": ["whether or not"],
    "not only": ["not just"],
}

PHRASES_LOOSE = {
    "i believe that": ["I think", "I'd say"],
    "i would argue that": ["I'd say", "I think"],
    "it is clear that": ["clearly", "obviously"],
    "it is evident that": ["clearly", "you can tell"],
    "one could argue": ["you could argue", "some would say"],
    "one might say": ["you could say"],
    "one must": ["you have to", "you've got to"],
    "one should": ["you should"],
    "individuals who": ["people who"],
    "a person who": ["someone who"],
    "is of great importance": ["matters a lot"],
    "is of the utmost importance": ["matters more than anything"],
    "in my opinion": ["I think", "personally", "if you ask me"],
    "from my perspective": ["the way I see it", "to me"],
    "it is possible that": ["maybe", "it might be that"],
    "there are several": ["there are a few"],
    "there are many": ["there are a lot of", "there are plenty of"],
    "a considerable amount": ["quite a lot", "a fair bit"],
}

# --------------------------------------------------------------------------
# Single words.
# --------------------------------------------------------------------------

WORDS_SAFE = {
    "utilize": ["use"],
    "utilizes": ["uses"],
    "utilized": ["used"],
    "utilizing": ["using"],
    "utilization": ["use"],
    "commence": ["start", "begin"],
    "commenced": ["started", "began"],
    "commencing": ["starting"],
    "terminate": ["end", "stop"],
    "terminated": ["ended", "stopped"],
    "facilitate": ["help", "ease", "support"],
    "facilitates": ["helps", "supports"],
    "facilitated": ["helped", "supported"],
    "demonstrate": ["show"],
    "demonstrates": ["shows"],
    "demonstrated": ["showed"],
    "demonstrating": ["showing"],
    "endeavor": ["try", "effort"],
    "endeavour": ["try", "effort"],
    "ascertain": ["find out", "work out"],
    "obtain": ["get"],
    "obtained": ["got"],
    "obtaining": ["getting"],
    "acquire": ["get", "pick up"],
    "acquired": ["got", "picked up"],
    "possess": ["have"],
    "possesses": ["has"],
    "sufficient": ["enough"],
    "insufficient": ["not enough"],
    "additional": ["extra", "more"],
    "numerous": ["many", "a lot of", "plenty of"],
    "myriad": ["countless", "tons of"],
    "plethora": ["glut", "flood"],
    "aforementioned": ["earlier", "above"],
    "subsequently": ["later", "then"],
    "previously": ["before", "earlier"],
    "currently": ["right now", "now"],
    "initially": ["at first", "to start"],
    "essentially": ["basically", "really"],
    "primarily": ["mostly", "mainly"],
    "predominantly": ["mostly", "mainly"],
    "frequently": ["often", "regularly"],
    "typically": ["usually", "normally"],
    "generally": ["usually", "mostly"],
    "particularly": ["especially"],
    "extremely": ["really", "very"],
    "incredibly": ["really", "very"],
    "exceptionally": ["really", "unusually"],
    "immensely": ["hugely", "really"],
    "vastly": ["hugely", "far"],
    "remarkably": ["surprisingly", "notably"],
    "undoubtedly": ["no doubt", "for sure"],
    "certainly": ["definitely", "for sure"],
    "arguably": ["maybe", "possibly"],
    "notably": ["especially"],
    "furthermore": ["also", "and"],
    "moreover": ["also", "plus"],
    "additionally": ["also", "plus"],
    "consequently": ["so"],
    "therefore": ["so"],
    "thus": ["so"],
    "hence": ["so"],
    "whilst": ["while"],
    "amongst": ["among"],
    "regarding": ["about", "on"],
    "concerning": ["about"],
    "pertaining": ["relating"],
    "assist": ["help"],
    "assists": ["helps"],
    "assisted": ["helped"],
    "assistance": ["help"],
    "attempt": ["try"],
    "attempts": ["tries"],
    "attempted": ["tried"],
    "require": ["need"],
    "requires": ["needs"],
    "required": ["needed"],
    "requirement": ["need"],
    "purchase": ["buy"],
    "purchased": ["bought"],
    "ensure": ["make sure"],
    "ensures": ["makes sure"],
    "ensuring": ["making sure"],
    "indicate": ["show", "suggest"],
    "indicates": ["shows", "suggests"],
    "indicated": ["showed"],
    "implement": ["build", "set up"],
    "implements": ["builds", "sets up"],
    "implemented": ["built", "set up"],
    "implementation": ["rollout", "build"],
    "methodology": ["method", "approach"],
    "functionality": ["features"],
    "capabilities": ["features"],
    "optimal": ["best"],
    "optimize": ["improve", "tune"],
    "optimizes": ["improves", "tunes"],
    "optimized": ["tuned", "improved"],
    "leverage": ["use", "lean on"],
    "leverages": ["uses", "leans on"],
    "leveraging": ["using"],
    "harness": ["use", "tap"],
    "harnessing": ["using", "tapping"],
    "foster": ["build", "encourage"],
    "fosters": ["builds", "encourages"],
    "fostering": ["building", "encouraging"],
    "underscore": ["highlight", "show"],
    "underscores": ["highlights", "shows"],
    "encompass": ["cover", "include"],
    "encompasses": ["covers", "includes"],
    "exemplify": ["show", "illustrate"],
    "exemplifies": ["shows", "illustrates"],
    "elucidate": ["explain", "spell out"],
    "articulate": ["explain", "put into words"],
    "mitigate": ["reduce", "soften"],
    "mitigates": ["reduces", "softens"],
    "alleviate": ["ease", "reduce"],
    "expedite": ["speed up"],
    "augment": ["add to", "boost"],
    "constitute": ["make up"],
    "constitutes": ["makes up"],
    "comprise": ["include", "make up"],
    "comprises": ["includes", "makes up"],
    "exhibit": ["show"],
    "exhibits": ["shows"],
    "yield": ["give", "produce"],
    "yields": ["gives", "produces"],
    "conclude": ["decide", "wrap up"],
    "determine": ["work out", "figure out"],
    "determines": ["works out", "decides"],
    "determined": ["worked out", "figured out"],
    "establish": ["set up", "build"],
    "established": ["set up", "built"],
    "maintain": ["keep", "keep up"],
    "maintains": ["keeps"],
    "retain": ["keep"],
    "retains": ["keeps"],
    "provide": ["give", "offer"],
    "provides": ["gives", "offers"],
    "provided": ["gave", "offered"],
    "enable": ["let", "allow"],
    "enables": ["lets", "allows"],
    "enabling": ["letting"],
}

WORDS_CASUAL = {
    "crucial": ["key", "critical", "big"],
    "pivotal": ["key", "central"],
    "vital": ["key", "critical"],
    "paramount": ["the top priority", "critical"],
    "essential": ["key", "necessary"],
    "significant": ["big", "major"],
    "substantial": ["big", "sizeable"],
    "considerable": ["big", "fair"],
    "comprehensive": ["full", "thorough", "complete"],
    "extensive": ["wide", "broad"],
    "robust": ["solid", "sturdy", "tough"],
    "seamless": ["smooth", "clean"],
    "innovative": ["new", "fresh", "inventive"],
    "groundbreaking": ["new", "first of its kind"],
    "transformative": ["big", "far reaching"],
    "revolutionary": ["radical", "new"],
    "intricate": ["complex", "tricky", "fiddly"],
    "nuanced": ["subtle", "layered"],
    "multifaceted": ["many sided", "complex"],
    "conduct": ["run", "carry out"],
    "conducted": ["run", "carried out"],
    "holistic": ["whole picture", "overall"],
    "meticulous": ["careful", "painstaking"],
    "unparalleled": ["unmatched", "like nothing else"],
    "unprecedented": ["never seen before", "new"],
    "invaluable": ["really useful", "priceless"],
    "profound": ["deep", "big"],
    "compelling": ["strong", "convincing"],
    "daunting": ["intimidating", "rough"],
    "myriad": ["countless"],
    "diverse": ["varied", "mixed"],
    "various": ["different", "a few"],
    "several": ["a few", "some"],
    "individuals": ["people"],
    "individual": ["person"],
    "persons": ["people"],
    "children": ["kids"],
    "purchase": ["buy"],
    "residence": ["home", "house"],
    "vehicle": ["car"],
    "approximately": ["about", "around"],
    "realm": ["world", "area"],
    "landscape": ["world", "scene"],
    "arena": ["space", "world"],
    "domain": ["area", "field"],
    "notion": ["idea"],
    "concept": ["idea"],
    "framework": ["setup", "structure"],
    "paradigm": ["model", "way of thinking"],
    "mechanism": ["way", "process"],
    "component": ["part", "piece"],
    "components": ["parts", "pieces"],
    "element": ["part", "piece"],
    "factor": ["reason", "part"],
    "aspect": ["side", "part"],
    "objective": ["goal", "aim"],
    "outcome": ["result"],
    "outcomes": ["results"],
    "benefit": ["upside", "plus"],
    "benefits": ["upsides", "perks"],
    "challenge": ["problem", "hurdle"],
    "challenges": ["problems", "hurdles"],
    "opportunity": ["chance", "opening"],
    "opportunities": ["chances", "openings"],
    "solution": ["fix", "answer"],
    "solutions": ["fixes", "answers"],
    "difficult": ["hard", "tough"],
    "simple": ["easy", "plain"],
    "rapid": ["fast", "quick"],
    "rapidly": ["fast", "quickly"],
    "commence": ["kick off", "start"],
    "sufficient": ["enough"],
    "prominent": ["well known", "big"],
    "renowned": ["well known", "famous"],
    "reveal": ["show"],
    "reveals": ["shows"],
    "observe": ["see", "watch"],
    "observed": ["saw", "noticed"],
    "perceive": ["see"],
    "assess": ["check", "size up"],
    "evaluate": ["check", "weigh"],
    "examine": ["look at", "go over"],
    "analyze": ["look at", "break down"],
    "analyse": ["look at", "break down"],
    "identify": ["spot", "find"],
    "identified": ["spotted", "found"],
    "recognize": ["see", "spot"],
    "comprehend": ["understand", "get"],
    "understand": ["get", "follow"],
    "inquire": ["ask"],
    "respond": ["reply", "answer"],
    "collaborate": ["work together", "team up"],
    "participate": ["take part", "join in"],
    "contribute": ["add", "chip in"],
    "encounter": ["run into", "hit"],
    "encountered": ["ran into", "hit"],
    "accomplish": ["get done", "pull off"],
    "achieve": ["hit", "reach"],
    "achieved": ["hit", "reached"],
    "eliminate": ["cut", "get rid of"],
    "reduce": ["cut", "bring down"],
    "modify": ["change", "tweak"],
    "alter": ["change"],
    "transform": ["change", "turn"],
    "represents": ["marks", "is"],
    "represent": ["mark", "stand for"],
    "reside": ["live", "sit"],
    "occur": ["happen"],
    "occurs": ["happens"],
    "occurred": ["happened"],
    "persist": ["stick around", "keep on"],
    "perform": ["do", "run"],
    "operate": ["run", "work"],
    "select": ["pick", "choose"],
    "selected": ["picked", "chose"],
    "prohibit": ["ban", "stop"],
    "attain": ["reach", "get"],
    "initiate": ["start", "kick off"],
    "finalize": ["finish", "wrap up"],
    "prioritize": ["put first", "focus on"],
    "emphasize": ["stress", "push"],
    "highlight": ["call out", "point to"],
    "illustrate": ["show"],
    "clarify": ["clear up", "spell out"],
    "summarize": ["sum up"],
}

WORDS_LOOSE = {
    "very": ["really", "pretty", "super"],
    "many": ["a lot of", "loads of", "plenty of"],
    "excellent": ["great", "really good"],
    "exceptional": ["great", "standout"],
    "outstanding": ["great", "standout"],
    "beneficial": ["helpful", "good"],
    "detrimental": ["bad", "harmful"],
    "advantageous": ["helpful", "worth it"],
    "unfortunate": ["bad luck", "a shame"],
    "fortunate": ["lucky"],
    "adequate": ["okay", "good enough"],
    "appropriate": ["right", "fitting"],
    "inappropriate": ["wrong", "off"],
    "accurate": ["right", "spot on"],
    "inaccurate": ["wrong", "off"],
    "immediately": ["right away", "straight away"],
    "eventually": ["in the end", "sooner or later"],
    "occasionally": ["now and then", "sometimes"],
    "constantly": ["all the time", "nonstop"],
    "entirely": ["totally", "completely"],
    "completely": ["totally", "flat out"],
    "definitely": ["for sure", "no question"],
    "probably": ["most likely"],
    "perhaps": ["maybe"],
    "somewhat": ["a bit", "kind of"],
    "slightly": ["a bit", "a touch"],
    "quite": ["pretty", "fairly"],
    "rather": ["pretty", "fairly"],
    "regarding": ["about"],
    "assist": ["help out"],
    "purchase": ["pick up", "buy"],
    "attempt": ["have a go at", "try"],
    "inform": ["tell"],
    "depart": ["leave"],
    "arrive": ["show up"],
    "remain": ["stay", "stick around"],
    "discover": ["find", "stumble on"],
    "consider": ["think about", "weigh up"],
    "believe": ["think", "reckon"],
    "realize": ["figure out"],
    "suggest": ["say", "point to"],
    "propose": ["put forward", "suggest"],
    "mention": ["bring up", "say"],
    "discuss": ["talk about", "go over"],
    "describe": ["lay out", "walk through"],
    "explain": ["walk through", "spell out"],
    "avoid": ["steer clear of", "stay away from"],
    "prevent": ["stop", "head off"],
    "continue": ["keep going", "carry on"],
    "complete": ["finish", "wrap up"],
    "begin": ["start", "kick off"],
    "assume": ["figure", "take it"],
    "appear": ["look", "seem"],
    "appears": ["looks", "seems"],
    "seem": ["look", "feel"],
}

# --------------------------------------------------------------------------
# Contractions. Applied at level >= 2.
# --------------------------------------------------------------------------

CONTRACTIONS = {
    "do not": "don't",
    "does not": "doesn't",
    "did not": "didn't",
    "is not": "isn't",
    "are not": "aren't",
    "was not": "wasn't",
    "were not": "weren't",
    "has not": "hasn't",
    "have not": "haven't",
    "had not": "hadn't",
    "will not": "won't",
    "would not": "wouldn't",
    "should not": "shouldn't",
    "could not": "couldn't",
    "cannot": "can't",
    "can not": "can't",
    "must not": "mustn't",
    "it is": "it's",
    "it has": "it's",
    "it will": "it'll",
    "that is": "that's",
    "that will": "that'll",
    "there is": "there's",
    "there has": "there's",
    "there will": "there'll",
    "here is": "here's",
    "what is": "what's",
    "who is": "who's",
    "let us": "let's",
    "i am": "I'm",
    "i have": "I've",
    "i will": "I'll",
    "i would": "I'd",
    "you are": "you're",
    "you have": "you've",
    "you will": "you'll",
    "you would": "you'd",
    "we are": "we're",
    "we have": "we've",
    "we will": "we'll",
    "we would": "we'd",
    "they are": "they're",
    "they have": "they've",
    "they will": "they'll",
    "they would": "they'd",
    "he is": "he's",
    "he will": "he'll",
    "she is": "she's",
    "she will": "she'll",
    "would have": "would've",
    "should have": "should've",
    "could have": "could've",
    "might have": "might've",
    "you are not": "you aren't",
}

# --------------------------------------------------------------------------
# Level >= 6 seasoning.
# --------------------------------------------------------------------------

# Dropped in before an adjective. "honestly" and "actually" belong at the front
# of a sentence, not here, so they live in OPENERS instead.
HEDGES = [
    "pretty", "fairly", "basically", "really", "kind of", "sort of",
    "more or less", "a bit",
]

# Dropped at the start of a sentence, mid-paragraph only.
OPENERS = [
    "Honestly, ", "To be fair, ", "That said, ", "Still, ", "And ",
    "But ", "So ", "Look, ", "Then again, ", "Truth is, ", "Now, ",
]

# A sentence already starting one of these does not get an opener bolted on
# top, or you end up with "That said on top of that, ...". Checked against the
# lowercased start of the sentence, so keep the entries in that form.
CONNECTIVE_STARTS = (
    "and ", "but ", "so ", "or ", "yet ", "plus", "also", "still", "though",
    "then ", "now,", "look,", "besides", "meanwhile", "however", "therefore",
    "that said", "that means", "then again", "on top of that", "in the end",
    "at the end of the day", "to be fair", "truth is", "honestly", "basically",
    "actually", "anyway", "first off", "finally", "in conclusion", "to wrap up",
    "to sum up", "all in all", "in short", "either way", "even so", "of course",
    "for example", "for instance", "in fact", "instead", "otherwise", "granted",
)

# Sentence-final tacks-on, used sparingly.
TAILS = [
    " at least", " I think", " really", " anyway", " in practice",
    " more or less", " for the most part",
]

# Hyphenated compounds that should stay hyphenated no matter the level:
# splitting them changes the meaning or reads as broken rather than sloppy.
HYPHEN_KEEP = {
    "x-ray", "e-commerce", "t-shirt", "u-turn", "re-entry", "re-elect",
    "co-op", "check-in", "well-being", "one-to-one", "far-fetched",
    "in-depth", "up-to-date", "twenty-one", "thirty-one", "self-aware",
    "mother-in-law", "father-in-law", "merry-go-round", "know-how",
}

# Hyphenated pairs that native typists routinely close up instead of spacing.
HYPHEN_JOIN = {
    "e-mail": "email",
    "on-line": "online",
    "web-site": "website",
    "data-base": "database",
    "co-worker": "coworker",
    "co-operate": "cooperate",
    "co-ordinate": "coordinate",
    "non-profit": "nonprofit",
    "multi-task": "multitask",
    "pre-existing": "preexisting",
    "de-brief": "debrief",
    "re-use": "reuse",
    "half-way": "halfway",
    "any-more": "anymore",
    "life-time": "lifetime",
}


def _merge(*tables):
    out = {}
    for table in tables:
        for key, value in table.items():
            out[key] = value
    return out


PHRASE_TIERS = (
    (1, PHRASES_SAFE),
    (3, PHRASES_CASUAL),
    (6, PHRASES_LOOSE),
)

WORD_TIERS = (
    (1, WORDS_SAFE),
    (3, WORDS_CASUAL),
    (6, WORDS_LOOSE),
)


def phrases_for_level(level):
    """Phrase table unlocked at ``level``."""
    return _merge(*[table for min_level, table in PHRASE_TIERS if level >= min_level])


def words_for_level(level):
    """Word table unlocked at ``level``."""
    return _merge(*[table for min_level, table in WORD_TIERS if level >= min_level])
